django_chatter/urls.py
from django.urls import path
from . import views

# Defined namespace for use on all templates
app_name = 'django_chatter'

urlpatterns = [
	path('', views.IndexView.as_view(), name = "index"),
	path('<str:uuid>/', views.ChatRoomView.as_view(), name = "chatroom"),

	#AJAX paths
	path('ajax/users-list/', views.users_list, name = "users_list"),
	path('ajax/get-chat-url/', views.get_chat_url, name = "get_chat_url"),
	path('ajax/get-messages/<str:uuid>/', views.get_messages, name="get_messages")
]

scholarship_portal/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth.forms import UserCreationForm

from Scholarship.views import index, scholarships, internships, exchange_programs, post, search, filterView, post_create, post_update, post_delete, registerPage, loginPage, logoutUser, contactPage

from subscribe.views import email_list_signup




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('scholarships/', scholarships, name='scholarship-list'),
    path('filter/', filterView, name='filter'),
    path('internships/', internships, name='internship-list'),
    path('exchange_programs/', exchange_programs, name='exchange_program-list'),
    path('search/', search, name='search'),
    path('contact/', contactPage, name='contact'),
    path('register/', registerPage, name="register"),
	path('login/', loginPage, name="login"),  
	path('logout/', logoutUser, name="logout"),
    path('email-signup/', email_list_signup, name='email-list-signup'),
    path('post/<id>/', post, name='scholarship-detail'),
    path('create/', post_create, name='scholarship-create'),
    path('post/<id>/update/', post_update, name='scholarship-update'),
    path('post/<id>/delete/', post_delete, name='scholarship-delete'),
    path('tinymce/', include('tinymce.urls')),
    # path('chat/', include('chat.urls', namespace='chat')),
    path('chat/', include('django_chatter.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_chatter/models.py
import uuid

from django.conf import settings
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
            on_delete=models.CASCADE, related_name='profile')
    last_visit = models.DateTimeField()


# This model is used to give date and time when a message was created/modified.
class DateTimeModel(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Room(DateTimeModel):
    id = models.UUIDField(primary_key=True,
            default=uuid.uuid4,
            editable=False)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL)

    def __str__(self):
        memberset = self.members.all()
        members_list = []
        for member in memberset:
            members_list.append(member.username)

        return ", ".join(members_list)


class Message(DateTimeModel):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, related_name='sender')
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    text = models.TextField()
    recipients = models.ManyToManyField(settings.AUTH_USER_MODEL,
        related_name='recipients')

    def __str__(self):
        return f'{self.text} sent by "{self.sender}" in Room "{self.room}"'

    class Meta:
        ordering = ['-id']

django_chatter/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse, Http404
from django.contrib.auth import logout, get_user_model
from django.core.exceptions import PermissionDenied
from django.conf import settings
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Room, Message
from .utils import create_room

# import the logging library
import logging

# Get an instance of a logger
logger = logging.getLogger(__name__)

def import_base_template():
	try:
		return settings.CHATTER_BASE_TEMPLATE
	except AttributeError as e:
		try:
			if settings.CHATTER_DEBUG == True:
				logger.info("django_chatter.views: "
				"(Optional) settings.CHATTER_BASE_TEMPLATE not found. You can "
				"set it to point to your base template in your settings file.")
		except AttributeError as e:
			logger.info("django_chatter.views: "
			"(Optional) settings.CHATTER_BASE_TEMPLATE not found. You can "
			"set it to point to your base template in your settings file.")
			logger.info("django_chatter.views: to turn off this message, set "
			"your settings.CHATTER_DEBUG to False.")
		return 'django_chatter/base.html'


class IndexView(LoginRequiredMixin, View):

	def get(self, request, *args, **kwargs):
		rooms_list = Room.objects.filter(members=request.user).order_by('-date_modified')
		if rooms_list.exists():
			latest_room_uuid = rooms_list[0].id
			return HttpResponseRedirect(
				reverse('django_chatter:chatroom', args=[latest_room_uuid])
			)
		else:
			# create room with the user themselves
			user = get_user_model().objects.get(username=request.user)
			room_id = create_room([user])
			return HttpResponseRedirect(
				reverse('django_chatter:chatroom', args=[room_id])
			)


# This fetches a chatroom given the room ID if a user diretly wants to access the chat.
class ChatRoomView(LoginRequiredMixin, TemplateView):
	template_name = 'django_chatter/chat-window.html'

	# This gets executed whenever a room exists
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		uuid = kwargs.get('uuid')
		try:
			room = Room.objects.get(id=uuid)
			user=get_user_model().objects.get(username=self.request.user)
		except Exception as e:
			logger.exception("\n\nException in django_chatter.views.ChatRoomView:\n")
			raise Http404("Sorry! What you're looking for isn't here.")
		all_members = room.members.all()
		if user in all_members:
			latest_messages_curr_room = room.message_set.all()[:50]
			if latest_messages_curr_room.exists():
				message = latest_messages_curr_room[0]
				message.recipients.add(user)
			if all_members.count() == 1:
				room_name = "Notes to Yourself"
			elif all_members.count() == 2:
				room_name = all_members.exclude(pk=user.pk)[0]
			else:
				room_name = room.__str__()
			context['room_uuid_json'] = kwargs.get('uuid')
			context['latest_messages_curr_room'] = latest_messages_curr_room
			context['room_name'] = room_name
			context['base_template'] = import_base_template()

			# Add rooms with unread messages
			rooms_list = Room.objects.filter(members=self.request.user)\
				.order_by('-date_modified')[:10]
			rooms_with_unread = []
			# Go through each list of rooms and check if the last message was unread
			# and add each last message to the context
			for room in rooms_list:
				try:
					message = room.message_set.all().order_by('-id')[0]
				except IndexError as e:
					continue
				if self.request.user not in message.recipients.all():
					rooms_with_unread.append(room.id)
			context['rooms_list'] = rooms_list
			context['rooms_with_unread'] = rooms_with_unread

			return context
		else:
			raise Http404("Sorry! What you're looking for isn't here.")


#The following functions deal with AJAX requests
@login_required
def users_list(request):
	if (request.is_ajax()):
		data_array = []
		for user in get_user_model().objects.all():
			data_dict = {}
			data_dict['id'] = user.pk
			data_dict['text'] = user.username
			data_array.append(data_dict)
		return JsonResponse(data_array, safe=False)


@login_required
def get_chat_url(request):
	user = get_user_model().objects.get(username=request.user)
	target_user = get_user_model().objects.get(pk=request.POST.get('target_user'))

	'''
	AI-------------------------------------------------------------------
		Use the util room creation function to create room for one/two
		user(s). This can be extended in the future to add multiple users
		in a group chat.
	-------------------------------------------------------------------AI
	'''
	if (user == target_user):
		room_id = create_room([user])
	else:
		room_id = create_room([user, target_user])
	return HttpResponseRedirect(
		reverse('django_chatter:chatroom', args=[room_id])
	)

# Ajax request to fetch earlier messages
@login_required
def get_messages(request, uuid):
	if request.is_ajax():
		room = Room.objects.get(id=uuid)
		if request.user in room.members.all():
			messages = room.message_set.all()
			page = request.GET.get('page')

			paginator = Paginator(messages, 20)
			try:
				selected = paginator.page(page)
			except PageNotAnInteger:
				selected = paginator.page(1)
			except EmptyPage:
				selected = []
			messages_array = []
			for message in selected:
				dict = {}
				dict['sender'] = message.sender.username
				dict['message'] = message.text
				dict['received_room_id'] = uuid
				dict['date_created'] = message.date_created.strftime("%d %b %Y %H:%M:%S %Z")
				messages_array.append(dict)

			return JsonResponse(messages_array, safe=False)

		else:
			return Http404("Sorry! We can't find what you're looking for.")
	else:
		return Http404("Sorry! We can't find what you're looking for.")

templates/django_chatter/base.html
<!--AI==========================================================
	This is the Base for all pages in the chat app. It contains
	the following CSS stylesheets:
		1) Bootstrap 4.1.2
		2) Chat app
		3) JQuery UI for formatting autocomplete elements proper
	and the following JS scripts:
		1) BootStrap 4.1.2
		2) JQuery
		3) JQuery UI
===========================================================AI-->


{% load static %}


<html>
{% include "head.html" %}
	<head>
		<meta charset="UTF-8">

		<!--Mobile first viewport tag-->
		<meta name="viewport"
		content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!--JQuery JS-->
		<script src = "https://code.jquery.com/jquery-3.3.1.min.js"></script>

		<!--FontAwesome-->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
		integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
		crossorigin="anonymous">

		<!--AI======================================================================
			We use JQuery UI to use its autocomplete function to dynamically
			produce a list of registered users for the current user to look through.
		=======================================================================AI-->
		<!--JQuery UI CSS-->
		<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
		<!--JQuery UI JS-->
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

		<!--AI==========================================================
			Chat App's CSS stylesheet link.
		===========================================================AI-->
		<link rel="stylesheet" href="{% static 'css/base.css' %}">
	{% block django_chatter_extrahead %}
	{% endblock django_chatter_extrahead %}
	</head>

		<!--AI==========================================================
			Child pages inherting this base must include their extra
			properties inside the following content block.
		===========================================================AI-->
		{% include "header.html" %}
		<body style="margin:0;">
		{% block django_chatter_content %}
		{% endblock django_chatter_content %}
		</body>


    {% include "footer.html" %}
</html>

templates/django_chatter/chat-window.html
<!--AI==========================================================
	Every chat session will have this html page rendered.
===========================================================AI-->

<!--Extends the Chat app base-->
{% extends base_template %}

<!--Django staticfiles functions are loaded using this tag-->
{% load static %}

<!--AI==========================================================
	Extra CSS that applies to this template.
===========================================================AI-->
{% block django_chatter_extrahead %}
	{{ block.super }}
	<title>{{room_name}} | Chatter</title>
	<link rel="stylesheet" href="{% static 'css/chat-window.css' %}">
	<!--Jquery-->
	<script src = "https://code.jquery.com/jquery-3.3.1.min.js"></script>
{% endblock django_chatter_extrahead %}

{% block django_chatter_content %}
{{ block.super }}
<div class="app-container">
	<div class="chat-container">
			<!--AI==========================================================
				This inherits the list of chats that a user belongs to.
			===========================================================AI-->
			<div class="chatroom-list-container chat-subsection">
				{% include 'django_chatter/chatroom-list.html' %}
			</div>

			<!--AI==========================================================
				The following contains the chat dialog div properties
			===========================================================AI-->
			<div class = "dialog-container chat-subsection">
				<div id = "room-title">
					<div class="back-button-container">
						<img id="back-button" src="{% static 'img/left-arrow.svg' %}">
					</div>
					<div>{{room_name}}</div>
				</div>
				<div id = "chat-dialog">
					<!--AI==========================================================
						Fetch latest 50 messages and display them properly.
					===========================================================AI-->
					{% for message in latest_messages_curr_room reversed %}
						{% if message.sender.username == user.username %}
							<div class="message-container">
								<div class="message message-sent">
									{{message.text}}
								</div>
								<div class="message message-sent message-date-created">
									{{message.date_created|date:"d M Y H:i:s e"}}
								</div>
							</div>
						{% else %}
							<div class="message-container">
								<div class="message-received-container">
									<div class="receiver-bubble">
										{{message.sender|make_list|first|title}}
									</div>
									<div class="message message-received">
										{{message.text}}
									</div>
								</div>
								<div class="message message-received message-date-created
									message-received-date-created">
									{{message.date_created|date:"d M Y H:i:s e"}}
								</div>

							</div>
						{% endif %}
					{% endfor %}
				</div>
				<div class = "input-container">
					<input type="text" id = "send-message" rows = "1"
						placeholder = "Type your message...">
					<div id="send-btn-parent">
						<img id="send-button" height="30px" role="button"
							src="{% static 'img/send-button.svg' %}">
					</div>
				</div>
			</div>
		</div>

	<!--AI==========================================================
		These JS files load after the page has loaded.
		1) searchuser.js: fetches a list of users from the server
		2) chat-window.js: contains websocket functions for this
			chat page.
	===========================================================AI-->
	</div>
</div>
<script>
	var room_id = '{{room_uuid_json}}';
	var get_room_url = '{% url "django_chatter:get_messages" uuid=room_uuid_json %}';
	var username = '{{user.username}}';
</script>
<script src = "{% static 'js/dateFormatter.js' %}"></script>
<script src = "{% static 'js/websocketHelpers.js' %}"></script>
<script src = "{% static 'js/chatSocket.js' %}"></script>
<script src = "{% static 'js/alertSocket.js' %}"></script>
<script src = "{% static 'js/chatWindow.js' %}"></script>
<script src = "{% static 'js/fetchMessages.js' %}"></script>
{% endblock django_chatter_content %}

templates/django_chatter/chatroom-list.html
<!--AI==========================================================
	This template displays the chat room list in every page
	that inherits in. The rooms_list variable is universal
	as it is created by chat/context_processors.py file.
===========================================================AI-->


{% load static %}
<link rel = "stylesheet" href = "{% static 'css/chatroom-list.css' %}">

<!-- select2 used to accommodate group chats later -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

<!--AI==========================================================
	The following div describes the Search bar to search
	for users as well as the name of the chatroom.
	===========================================================AI-->
	<div class="chatroom-list-title">Chats</div>
	<div class="search">
		<form class="search-form" action="{% url 'django_chatter:get_chat_url' %}" method="post">
			{% csrf_token %}
			<!-- <input id = "searchbar" placeholder = "Username"></input>
			<button id = "user-selected">Go</button><br /> -->
			<select class="select-chat-user" name="target_user">
				<option></option>
			</select>
			<button type="submit" name="button" class="select-chat-button">Go</button>
		</form>
	</div>

<!--AI==========================================================
	The following block represents the list of chatrooms at the left
===========================================================AI-->
<div class = "chatroom-list">
	{% for room in rooms_list %}
		<a class="chat-link list-room" id='{{room.id}}'
			href="{% url 'django_chatter:chatroom' uuid=room.id %}">

			{% if room.id in rooms_with_unread %}
			<div style='font-weight: bold;' class = 'chat-list-item'>
			{% else %}
			<div class='chat-list-item'>
			{% endif %}
				<div class="chat-list-title">
					{% if room.members.all|length == 2 %}

						{% for user in room.members.all %}

							{% if user != request.user %}
								{{user}}
							{% endif %}

						{% endfor %}

					{% else %}
							{{room}}
					{% endif %}
				</div>

				<div class="chat-list-last-message">
					{% with room.message_set.all.0 as message %}
						{% if message.sender == request.user %}
							You: {{message.text}}
						{% else %}
							{{message.sender}}: {{message.text}}
						{% endif %}
					{% endwith %}
				</div>

			</div>
		</a>

	{% endfor %}
</div>

<script>
	var get_user_url = '{% url "django_chatter:users_list" %}';
	var get_chat_url = '{% url "django_chatter:get_chat_url" %}';
	var chatter_index = '{% url "django_chatter:index" %}';
</script>
<script src = "{% static 'js/searchUser.js' %}"></script>

templates/django_chatter/index.html
<!--AI==========================================================
	This page is the index page shown right when the user
	logs in but hasn't opened a room to chat in yet.
	Might become redundant in the future.
===========================================================AI-->

{% extends base_template %}
{% load static %}
{% block extrahead %}
	{{ block.super }}
	<link rel="stylesheet" href = "{% static 'css/index.css' %}">
{% endblock extrahead %}

{% block content %}
	{{ block.super }}
	<!--AI==========================================================
		This includes the list of rooms that the user belongs to.
	===========================================================AI-->
	{% include 'django_chatter/chatroom-list.html' %}

	<!--AI==========================================================
		This is the space that gives instruction to the user as to
		what to do when the user is on the index page.
	===========================================================AI-->
	<div class = "chat-section">
		<h3>Select a Chat to get started.</h3>
		<h6>Or type in a user's username you want to chat with.</h6>
	</div>

	<!--AI==========================================================
		JS that generates list of users for the user to search.
	===========================================================AI-->
	<script src = "{% static 'js/index.js' %}"></script>
{% endblock content %}